mileweb/docs-content-cdn

- docs/portal/accessing-portal/logging-in.md
- docs/portal/certificates/creating-certificates.md
- docs/portal/certificates/deploying-certificates.md
- docs/portal/certificates/updating-certificates.md
- docs/portal/content-management.md
> Pull Request for Day's Work

- docs/portal/certificates/creating-certificates.md
Changed "Cipher type" to "Public Key Algorithm"
> Revised per GUI change

- docs/portal/certificates/overview.md
Added undeploy links to to the last 2 bullets under Certificate Actions.
> Added two links

- docs/portal/certificates/overview.md
Added two undeploy links to the last 2 bullets
> Added two undeploy links to the last 2 bullets

- docs/manifest.json
After this pull request will be merged we should rename this repo to `docs-content-cdn` according to the new changed in `docs-app`.
> Added metadata

- docs/portal/reports.md
This upload addresses Julia Korsun's comment that protocol was mentioned in the field descriptions after the first Report screenshot.
> addresses NCP-2277

- docs/edge-logic/supported-variables.md
- docs/manifest.json
Please help review the supported-variables.md file and the manifest.json file.  Thanks.
> added supported variables 

- docs/recipes/secure-delivery.md
These are my edits to Bin's security document.
> Marc's edits

- docs/edge-logic/faq.md
Please help to review and merge.
> minor change, fixed a typo

- docs/edge-logic/faq.md
- docs/edge-logic/supported-directives.md
Recent updates to be merged to production.
> Recent updates to be merged to production by 4/22

- docs/portal/edge-configurations/managing-properties.md
- docs/portal/traffic-management/overview.md
Burton, kindly review and reply with feedback or approve. Thank you.
> Updates per Release30Apr2021

- apispec/openapi.json
I"m going to delete the old pull request containing sprint 108 updates since this has both sprint 108 and 109
> NCAS-2820 sprint 109 and sprint 108 updates

- en/docs/manifest.json
Updating the manifest.js to test Routing. Local test.
> Updating Manifest Links to Test Routing

- docs/release-notes.md
I created these CDN360 release notes based on internal release notes.  I added some details including relevant links (primarily to internal documentation) ; cleaned up some text ; and removed some information not meant for public consumption.  Note there is a separate task, NGDOC-93, to create a link to this information.
> Burton ngdoc88

- cn/docs/manifest.json
- en/docs/manifest.json
Adding the Release Notes to Manifest
> Ele ncdoc 88

- zh/docs/edge-logic/hello-world.md
Keven's modification on hello-world.md
> Test Github

- en/apispec/openapi.json
- zh/apispec/openapi.json
I update the links on the flow chart to fix the broken image.
> NCPROD-21 #Updating link to flowchart in both languages

- en/apispec/openapi.json
- zh/apispec/openapi.json
Updating the flow chart links to fix the image looking broken.
> NCPROD-21 Updating the flow chart links

- en/apispec/openapi.json
- zh/apispec/openapi.json
I forgot that at the moment all images are coming from EN. We will rework logic once we decide to translate images.
> NCPROD-21 Updating Flowchar img link back to EN

- en/docs/portal/edge-configurations/managing-properties.md
- zh/docs/portal/edge-configurations/managing-properties.md
Burton, please confirm that the link should work on docdev. Thank you.
> fixed link to API

- en/docs/portal/content-management.md
- zh/docs/portal/content-management.md
Burton, please confirm that the content management topic is bug-free.
> Revised figure reference

- en/docs/portal/content-management.md
- zh/docs/portal/content-management.md
Burton, let's see whether this upload fixes the problem in the Content Management topic.
> Fixed 2 images

- en/docs/portal/content-management.md
- zh/docs/portal/content-management.md
Fixed 2 internal cross-reference links in the Content Management topic.
> Fixed 2 internal cross-reference links

- en/docs/portal/content-management.md
- zh/docs/portal/content-management.md
Burton, I deleted the space and found the delimiter to use to eliminate the frowning face"
> Deleted space in the scheme pattern

- en/docs/release-notes.md
- zh/docs/release-notes.md
Some links are to API help that isn't yet updated, but I think you can check the text.
> NGDOC-136 #comment added release notes for January 21, 2022 release

- en/docs/portal/content-management/managing-prefetch-requests.md
I revised the wording for Regions in the table below step 3 in the Creating a Prefetch Request topic to confirm with Burton's suggestion.
> Revised region text

- en/docs/manifest.json
Revised file to see whether it posts to docdev.
> Updated json file

- en/docs/portal/reports/generating-reports.md
Attempt to fix block preventing online help from appearing in docdev.
> Updated path in topic

- en/docs/portal/edge-configurations/managing-properties.md
- zh/docs/portal/edge-configurations/managing-properties.md
Fixed two topics to correct numbering under Using Properties to Configure the Edge > Using the Advanced Filter Icon.
> fixed Using Properties to Configure the Edge

- zh/docs/manifest.json
I updated the paths in the json file. Please approve so we can see whether the error is corrected.
> revised paths in json file

- zh/docs/manifest.json
This file has been revised to work on docdev.
> Fixed Chinese language JSON file

- en/docs/portal/accessing-portal/navigating-ui.md
Fixed two links under Content Management.
> fixed two links

- en/apispec/openapi.json
- en/docs/edge-logic/supported-directives.md
- en/docs/release-notes.md
- zh/apispec/openapi.json
- zh/docs/edge-logic/supported-directives.md
- zh/docs/release-notes.md
These include the newest release notes and updated CDN Pro API specification.
> Merge latest changes to production

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
Cross reference proxy_cache_max_stale and proxy_cache_background_update
> Bin max stale

- en/apispec/openapi.json
- zh/apispec/openapi.json
Push the changes tested by QA on another environment to docdev.quantil.com
> NCAS-3762 #comment update docdev with the latest API spec

- en/docs/edge-logic/supported-directives.md
Added description of ENCRYPT_SYMM.
Does this sound OK?
If yes, we'll still need a Chinese translation in the corresponding file.
> Burton ncp2603

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
@nibinqtl @burtonquantil Added a new directive upstream_origin_only. Please help review.
> NGDOC-210 Add upstream_origin_only

- en/docs/manifest.json
- zh/docs/manifest.json
@burtonquantil Pls help review.
> NGDOC-212 Add route for the api-rate-limiting page

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
@nibinqtl @burtonquantil Pls review
> NCCS-4225 Make some directives available as base directives

- en/apispec/openapi.json
- zh/apispec/openapi.json
Let's finally get  all the changes to docdev.quantil.com before we merge to production.
> NCAS-4145 #comment update to the latest API spec

- en/docs/portal/reports/generating-reports.md
Fixed the display of the image so it  is next to the associated line of text.
I tested locally.
> NGDOC-234 #comment tried to move line to make it look better

- en/docs/edge-logic/faq.md
- zh/docs/edge-logic/faq.md
@nibinqtl Fix an error. Please review.
> NGDOC-232 fix-an-error-in-code-snippet

- en/apispec/openapi.json
- en/docs/release-notes.md
- zh/apispec/openapi.json
- zh/docs/release-notes.md
Revision to reflect our most recently deployed release
> Push latest release notes and API spec update to production

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
> NCAS-4756 remove origin_selection_algorithm

- en/apispec/openapi.json
Checking if it can be rendered correctly on the documentation staging server.
> NCAS-4801 #comment check if English version with corrected example works

- en/apispec/openapi.json
- en/docs/release-notes.md
- zh/apispec/openapi.json
- zh/docs/release-notes.md
Updated with changes related to our latest release
> Burton ngdoc268

- en/docs/edge-logic/supported-directives.md
> NGDOC-258 Revisions per Burton's review

- en/apispec/openapi.json
- en/docs/release-notes.md
- zh/apispec/openapi.json
- zh/docs/release-notes.md
Updated to reflect changes in Release07Jun2024
> NGDOC-275 #comment updated release notes and API spec

- en/apispec/openapi.json
> Burton ncas4900

- en/docs/recipes/aws-bucket.md
- zh/docs/recipes/aws-bucket.md
Rendering of the text was not working as expected though our markup was the same as used elsewhere on the page.
This tries to force the HTML tag to be used.
> Burton ngdoc298

- en/apispec/openapi.json
- en/docs/release-notes.md
- zh/apispec/openapi.json
- zh/docs/release-notes.md
These reflect the latest release.
> Merge the lastest to production

- en/docs/edge-logic/built-in-variables.md
- en/docs/edge-logic/edge-node-structure-upgrade.md
- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/built-in-variables.md
- zh/docs/edge-logic/edge-node-structure-upgrade.md
- zh/docs/edge-logic/supported-directives.md
@nibinqtl @burtonquantil Please review.
I take the chance to reduce some linebreaks in those nginx config examples on the page: Upgrade of edge node structure.
> ngdoc-314 deprecate lbLogic

- en/docs/edge-logic/faq.md
- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/built-in-variables.md
- zh/docs/edge-logic/faq.md
- zh/docs/edge-logic/supported-directives.md
@nibinqtl @burtonquantil Please review. Related Jira tasks:
https://quantil.atlassian.net/browse/NGDOC-322
https://quantil.atlassian.net/browse/NGDOC-323
> NGDOC-323 NGDOC-322

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
@nibinqtl @burtonquantil Please review
> NCAS-5290 mention policy param for origin_set_header

- en/docs/edge-logic/supported-directives.md
- zh/docs/edge-logic/supported-directives.md
> fix the syntax of add_header directive
